demultiplex: False
min: 100
max: 10000
quality: 15
trim_primers: True
primer_error_rate: 0.2
min_abundance: 0.0001
clustering: False
cluster_perc: 0.97
rank: species
threads: 2
group: ITS_fun #18_nem, 16S_bac or ITS_fun
barcode_file: barcode_files.txt
input_file: test_dataset_16S.fastq
forward_primer: AGAGTTTGATCMTGGCTCAG
reverse_primer: AAGTCGTAACAAGGTAACCG
classifier: emu #emu or vsearch


####metabarcoding primers#####
#18S nematodes (van himbeeck et al.) - forward primer: ctcaaagattaagccatgc; reverse primer: gctaccttgttacgactttt
#16S bacteria - forward primer: AGAGTTTGATCMTGGCTCAG; reverse primer: AAGTCGTAACAAGGTAACCG
#note that ITS primer trimming is not needed due to ITS extraction with ITS extract